name: inkleinelevator-server

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inkleinelevator-server:latest
    platform: linux/amd64
    container_name: ink-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/postgres}
    ports:
      - "${PORT:-5001}:${PORT:-5001}"
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"
    networks:
      - in_network

networks:
  in_network:
    external: true
    name: ${DOCKER_NETWORK:-root_in_network}
