import { Injectable } from '@nestjs/common';
import { MailService } from 'src/mail/mail.service';
import { PrismaService } from 'src/prisma/prisma.service';
import { RequestMaintenanceDto } from './dto/request-maintenance.dto';

@Injectable()
export class MaintenanceRequestService {
  constructor(
    private prisma: PrismaService,
    private mailService: MailService,
  ) {}

  async sendMaintenanceRequestMail(payload: RequestMaintenanceDto) {
    const contact = await (this.prisma as any).contactMessage.create({
      data: {
        firstName: payload.contactName,
        lastName: `(${payload.companyName})`,
        email: payload.email,
        phoneNumber: payload.phone,
        subject: `Elevator Maintenance Contract Request - ${payload.companyName}`,
        message: `
Building Address: ${payload.buildingAddress}
Building Type: ${payload.buildingType}
Number of Elevators: ${payload.numberOfElevators}
Manufacturer: ${payload.elevatorManufacturer || 'N/A'}
Elevator Type: ${payload.elevatorType}
Approximate Age: ${payload.approximateAge || 'N/A'}
Current Provider: ${payload.currentProvider || 'N/A'}
Contract Expiration: ${payload.contractExpirationDate || 'N/A'}
Desired Start Date: ${payload.desiredStartDate || 'N/A'}
Notes: ${payload.additionalNotes || 'None'}
Documents: ${payload.documents?.join(', ') || 'None'}
        `.trim(),
      },
    });

    const documentsListHtml =
      payload.documents && payload.documents.length > 0
        ? `<ul>${payload.documents
            .map(
              (doc, idx) =>
                `<li><a href="${doc}" target="_blank">Document ${idx + 1}</a></li>`,
            )
            .join('')}</ul>`
        : '<p>None attached</p>';

    const html = `
      <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;">
        <div style="background-color: #0A1A3A; padding: 20px; text-align: center; color: #ffffff;">
          <h2 style="margin: 0; color: #5CE1E6;">New Elevator Maintenance Contract Request</h2>
          <p style="margin: 5px 0 0 0; font-size: 14px; color: #d0d0d0;">Opportunity Evaluation Details</p>
        </div>

        <div style="padding: 24px; background-color: #ffffff;">
          <h3 style="border-bottom: 2px solid #5CE1E6; padding-bottom: 6px; color: #0A1A3A;">1. Company & Contact Information</h3>
          <p><strong>Company / Building Name:</strong> ${payload.companyName}</p>
          <p><strong>Contact Name:</strong> ${payload.contactName}</p>
          <p><strong>Email Address:</strong> <a href="mailto:${payload.email}">${payload.email}</a></p>
          <p><strong>Phone Number:</strong> ${payload.phone}</p>

          <h3 style="border-bottom: 2px solid #5CE1E6; padding-bottom: 6px; color: #0A1A3A; margin-top: 24px;">2. Building & Elevator Details</h3>
          <p><strong>Building Address:</strong> ${payload.buildingAddress}</p>
          <p><strong>Building Type:</strong> ${payload.buildingType}</p>
          <p><strong>Number of Elevators:</strong> ${payload.numberOfElevators}</p>
          <p><strong>Elevator Manufacturer:</strong> ${payload.elevatorManufacturer || 'N/A'}</p>
          <p><strong>Elevator Type:</strong> ${payload.elevatorType}</p>
          <p><strong>Approximate Age of Elevators:</strong> ${payload.approximateAge || 'N/A'}</p>

          <h3 style="border-bottom: 2px solid #5CE1E6; padding-bottom: 6px; color: #0A1A3A; margin-top: 24px;">3. Current Contract & Schedule</h3>
          <p><strong>Current Maintenance Provider:</strong> ${payload.currentProvider || 'N/A'}</p>
          <p><strong>Current Contract Expiration Date:</strong> ${payload.contractExpirationDate || 'N/A'}</p>
          <p><strong>Desired Start Date for New Contract:</strong> ${payload.desiredStartDate || 'N/A'}</p>

          <h3 style="border-bottom: 2px solid #5CE1E6; padding-bottom: 6px; color: #0A1A3A; margin-top: 24px;">4. Additional Notes & Attachments</h3>
          <p><strong>Notes / Special Concerns:</strong></p>
          <div style="background-color: #f9f9f9; padding: 12px; border-radius: 4px; border-left: 4px solid #5CE1E6;">
            ${payload.additionalNotes || 'No notes provided.'}
          </div>
          <p style="margin-top: 16px;"><strong>Attached Files / Documents:</strong></p>
          ${documentsListHtml}
        </div>

        <div style="background-color: #f4f6f8; padding: 16px; text-align: center; font-size: 12px; color: #777; border-top: 1px solid #e0e0e0;">
          This email was automatically generated by in-Klein Elevators Maintenance Request System.
        </div>
      </div>
    `;

    // Target recipient: process.env.ADMIN_EMAIL, SMTP_USER, or Kleinelevator@gmail.com
    const recipientEmail =
      process.env.ADMIN_EMAIL ||
      process.env.SMTP_USER ||
      'Kleinelevator@gmail.com';

    await this.mailService.sendMessage(
      recipientEmail,
      `Elevator Maintenance Contract Request: ${payload.companyName}`,
      html,
    );

    return {
      message: 'Maintenance request submitted successfully',
      data: contact,
    };
  }

  async getAllMaintenanceRequests() {
    return (this.prisma as any).contactMessage.findMany({
      where: {
        subject: {
          startsWith: 'Elevator Maintenance Contract Request',
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
  }

  async getMaintenanceRequestById(id: string) {
    return (this.prisma as any).contactMessage.findUnique({
      where: {
        id,
      },
    });
  }
}
